server:
  port: 10001
  servlet:
    context-path: /
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: user
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring-cloud?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    database: mysql
    properties:
      show-sql: true
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.CamelCaseToUnderscoresNamingStrategy
      open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  main:
    #允许存在多个Feign调用相同Service的接口
    allow-bean-definition-overriding: true
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
  sleuth:
    sampler:
      probability: 1.0 # 采样比率
  zipkin:
    base-url: http://127.0.0.1:9411/ # zipkin server的请求地址
    discoveryClientEnabled: false # 让注册中心把它当作一个URL,而不是当作服务名
logging:
  level:
    root: info
    cn.newbeedaly.user: debug
  config: classpath:logback-spring-dev.xml
  logback:
    rollingpolicy:
      max-file-size: 250MB
      max-history: 7
      total-size-cap: 1GB
      clean-history-on-start: true
# feign
feign:
  httpclient:
    enabled: true
# user
uc:
  security:
    enable: true
    url-decision-enable: true
    url-white-list:
      - /user/login # 登录
      - /user/refreshToken # 刷新token
      - /user/validToken #验证token
server-name: user
